- hosts: all
  become: yes
  tasks:
   - name: install remote apt deps
     apt:
      pkg: 
      - apt-transport-https
      - ca-certificates
      - gnupg2
      - software-properties-common
      state: present

   - name: Send gpg key for docker and Kubernetes
     copy:
       src: "{{ item }}"
       dest: /tmp
     with_items:
       - docker.key
       - Kubernetes.gpg

   - name: add Docker apt-key
     apt_key:
       file: /tmp/docker.key
       state: present

   - name: add Docker's APT repository
     apt_repository:
      repo: deb https://download.docker.com/linux/debian stretch stable
      state: present
      filename: 'docker'
       
   - name: add Kubernetes apt-key
     apt_key:
       file: /tmp/Kubernetes.gpg
       state: present

   - name: add Kubernetes' APT repository
     apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: 'kubernetes'

   - name: clear apt cache
     #sudo: true
     shell: 'find /var/lib/apt/lists -maxdepth 1 -type f -exec rm -v {} \;'

   - name: update cache
     apt: 
       update_cache: true

   - name: Install Docker
     apt:
       name: docker-ce
       state: present

   - name: install kubernetes-cni
     apt:
       name: kubernetes-cni=0.8.6-00
       state: present

   - name: install kubelet
     apt:
       name: kubelet=1.19.0-00
       state: present

   - name: install kubeadm
     apt:
       name: kubeadm=1.19.0-00
       state: present

- hosts: master
  become: yes
  tasks:
   - name: install kubectl
     apt:
       name: kubectl=1.19.0-00
       state: present
       force: yes
